# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 03:23
from __future__ import unicode_literals

import core.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', core.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', core.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('link', models.URLField(blank=True, max_length=255)),
                ('published', models.DateTimeField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='feeds.Feed')),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set([('feed', 'link')]),
        ),
    ]
