# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='href',
            field=models.URLField(),
        ),
    ]
