# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 14:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entry',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='feeds.Feed'),
        ),
        migrations.AddField(
            model_name='content',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='feeds.Entry'),
        ),
        migrations.AlterUniqueTogether(
            name='feed',
            unique_together=set([('href', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set([('feed', 'href')]),
        ),
    ]
