# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='uid',
        ),
        migrations.AddField(
            model_name='entry',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
