# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='href',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='feed',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
