# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_auto_20170419_0454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='feed',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='feed',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='feed',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
