# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_auto_20170506_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
