# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_entry_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='entry',
        ),
        migrations.AddField(
            model_name='entry',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
