# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_entry_string_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='string_summary',
            field=models.TextField(blank=True),
        ),
    ]
