# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_auto_20170419_0458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='description',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='link',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='summary',
        ),
    ]
