# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 07:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeds', '0003_auto_20170507_0735'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feed',
            unique_together=set([('href', 'user')]),
        ),
    ]
