# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_auto_20170507_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='href',
            field=models.URLField(max_length=255),
        ),
    ]
