# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_auto_20170519_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='uid',
            field=models.CharField(blank=True, editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='uid',
            field=models.CharField(blank=True, editable=False, max_length=255, unique=True),
        ),
    ]
