# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_auto_20170422_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='href',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
