# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_auto_20170520_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='uid',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='uid',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
