# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_auto_20170527_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
