# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 20:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeds', '0006_auto_20170422_0604'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feed',
            unique_together=set([('user', 'href')]),
        ),
    ]
