# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 00:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_auto_20170521_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('-published',)},
        ),
    ]
