# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_entry_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
