# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_auto_20170422_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='href',
            new_name='link',
        ),
    ]
