# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0008_auto_20170422_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('published',)},
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set([('feed', 'link')]),
        ),
    ]
