# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0008_auto_20170508_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='html_href',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='href',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='feed',
            name='href',
            field=models.URLField(),
        ),
    ]
