# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0009_auto_20170509_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
