# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0009_auto_20170422_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('-published',)},
        ),
    ]
