# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0010_auto_20170513_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='last_fetch',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
