# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0010_auto_20170422_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='etag',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='feed',
            name='last_modified',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
