# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 03:44
from __future__ import unicode_literals

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0011_feed_last_fetch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='last_fetch',
            field=models.DateTimeField(default=core.utils.now),
        ),
    ]
