# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0012_auto_20170514_0344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={},
        ),
    ]
