# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 02:11
from __future__ import unicode_literals

import core.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0013_auto_20170514_0445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', core.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', core.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('base', models.URLField(blank=True)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(blank=True, max_length=255)),
                ('value', models.TextField(blank=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.Entry')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
