# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0014_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='feeds.Entry'),
        ),
    ]
